LANGUAGES = {
    ####################
    ## PORTUGUES (BR) ##
    ####################
    'pt': {
        # Menu principal
        'Dashboard': 'Dashboard',
        'Painel': 'Painel',
        'Pesquisa': 'Pesquisa',
        'Configurações': 'Configurações',
        'Sair': 'Sair',
        
        # Login
        'Usuário': 'Usuário',
        'Senha': 'Senha',
        'Entrar': 'Entrar',
        'Credenciais inválidas': 'Credenciais inválidas',
        'Preencha todos os campos': 'Preencha todos os campos',
        'Código MFA inválido': 'Código MFA inválido',
        'Coleta de dados iniciada, aguarde alguns minutos.': 'Coleta de dados iniciada, aguarde alguns minutos.',
        
        #Dashboard
        'Total de Máquinas': 'Total de Máquinas',
        'Ativas': 'Ativas',
        'Inativas': 'Inativas',
        'Atividade': 'Atividade',
        'Processos': 'Processos',
        'Nenhum dado disponível': 'Nenhum dado disponível',
        'Carregando dados...': 'Carregando dados...',
        'Sistemas Operacionais': 'Sistemas Operacionais',
        'Processadores': 'Processadores',
        'Memória RAM': 'Memória RAM',
        'Portas de Rede Mais Comuns': 'Portas de Rede Mais Comuns',
        'Processos Mais Comuns': 'Processos Mais Comuns',
        'Distribuição por Grupos': 'Distribuição por Grupos',
        'Máquinas Recentemente Sincronizadas': 'Máquinas Recentemente Sincronizadas',
        'Ver todas': 'Ver todas',
        'Sistema': 'Sistema',
        'Evolução Temporal - Máquinas Ativas e Inativas': 'Evolução Temporal - Máquinas Ativas e Inativas',
        
        # Painel de máquinas
        'Máquinas': 'Máquinas',
        'Detalhes': 'Detalhes',
        'Voltar': 'Voltar',
        'Hostname': 'Hostname',
        'IP Address': 'Endereço IP',
        'Inativo': 'Inativo',
        'Ativo': 'Ativo',
        'Sistema Operacional': 'Sistema Operacional',
        'Kernel': 'Kernel',
        'Arch': 'Arquitetura',
        'Processador': 'Processador',
        'Núcleos': 'Núcleos',
        'Memória (GB)': 'Memória (GB)',
        'Status': 'Status',
        'Última Atividade': 'Última Atividade',
        'resultado(s) encontrado(s)': 'resultado(s) encontrado(s)',
        'Nenhum resultado encontrado': 'Nenhum resultado encontrado',
        'Tente ajustar sua pesquisa': 'Tente ajustar sua pesquisa',
        'Pesquisar Máquinas': 'Pesquisar Máquinas',
        'Pesquisar': 'Pesquisar',
        'Pesquisar por hostname, SO ou processador...': 'Pesquisar por hostname, SO ou processador...',
        
        
        # Machine Details
        'Informações Básicas': 'Informações Básicas',
        
        # Configurações
        'Exportar PDF': 'Exportar PDF',
        'Sincronizar com Wazuh': 'Sincronizar com Wazuh',
        'Notificações': 'Notificações',
        'Segurança': 'Segurança',
        'Autenticação em Duas Etapas': 'Autenticação em Duas Etapas',
        'Configurar MFA': 'Configurar MFA',
        'Gerar PDF': 'Gerar PDF',
        'Cancelar': 'Cancelar',
        'Incluir detalhes completos': 'Incluir detalhes completos',
        'Sincronize os dados do inventário com o Wazuh Manager para manter todas as informações atualizadas.': 'Sincronize os dados do inventário com o Wazuh Manager para manter todas as informações atualizadas.',
        'Configure suas preferências de notificação para receber alertas importantes.': 'Configure suas preferências de notificação para receber alertas importantes.',
        'Exportar Relatório PDF': 'Exportar Relatório PDF',
        'Exportar um relatório completo em PDF com todas as informações do sistema': 'Exportar um relatório completo em PDF com todas as informações do sistema',
        'Escolha as opções para o relatório:': 'Escolha as opções para o relatório:',
        'Configure a autenticação de dois fatores (MFA) para aumentar a segurança.': 'Configure a autenticação de dois fatores (MFA) para aumentar a segurança.',
        'MFA está ': 'MFA está',
        'habilitada': 'habilitada',
        'desabilitada': 'desabilitada',
        'Desabilitar MFA': 'Desabilitar MFA',
        'Código de 6 dígitos': 'Código de 6 dígitos',
        'Desabilitar MFA': 'Desabilitar MFA',
        'Habilitar MFA': 'Habilitar MFA',
        'Secret': 'Chave Secreta',
        'Verificar': 'Verificar',
        'Cancelar': 'Cancelar',
        
        # Detalhes da máquina
        'Informações Básicas': 'Informações Básicas',
        'Hardware': 'Hardware',
        'Network interfaces': 'Interfaces de Rede',
        'Network ports': 'Portas de Rede',
        'Network settings': 'Configurações de Rede',
        'Installed Packages': 'Pacotes Instalados',
        'Running Processes': 'Processos em Execução',
        'Interface': 'Interface',
        'MAC': 'MAC',
        'State': 'Estado',
        'MTU': 'MTU',
        'Type': 'Tipo',
        'Local port': 'Porta Local',
        'Local IP': 'IP Local',
        'Process': 'Processo',
        'PID': 'PID',
        'Address': 'Endereço',
        'Netmask': 'Máscara de Rede',
        'Proto': 'Protocolo',
        'Broadcast': 'Broadcast',
        'Name': 'Nome',
        'Version': 'Versão',
        'Description': 'Descrição',
        'Architecture': 'Arquitetura',
        'Format': 'Formato',
        'User': 'Usuário',
        'Command': 'Comando',
        
    },
    #############
    ## ENGLISH ##
    #############
    'en': {
        # Menu principal
        'Dashboard': 'Dashboard',
        'Painel': 'Machines',
        'Pesquisa': 'Search',
        'Configurações': 'Settings',
        'Sair': 'Logout',
        
        # Login
        'Usuário': 'Username',
        'Senha': 'Password',
        'Entrar': 'Login',
        'Credenciais inválidas': 'Invalid credentials',
        'Preencha todos os campos': 'Please fill all fields',
        'Código MFA inválido': 'Invalid MFA code',
        'Coleta de dados iniciada, aguarde alguns minutos.': 'Data collection started, please wait a few minutes.',
        
        #Dashboard
        'Total de Máquinas': 'Total of Machines',
        'Ativas': 'Active',
        'Inativas': 'Inactive',
        'Atividade': 'Activity',
        'Processos': 'Processes',
        'Nenhum dado disponível': 'No data available',
        'Carregando dados...': 'Loading data...',
        'Sistemas Operacionais': 'Operating Systems',
        'Processadores': 'Processors',
        'Memória RAM': 'RAM Memory',
        'Portas de Rede Mais Comuns': 'Most Common Network Ports',
        'Processos Mais Comuns': 'Most Common Processes',
        'Distribuição por Grupos': 'Distribution by Groups',
        'Máquinas Recentemente Sincronizadas': 'Recently Sync Machines',
        'Ver todas': 'See all',
        'Sistema': 'System',
        'Evolução Temporal - Máquinas Ativas e Inativas': 'Temporal Evolution - Active and Inactive Machines',
        
        # Painel de máquinas
        'Máquinas': 'Machines',
        'Detalhes': 'Details',
        'Voltar': 'Back',
        'Inativo': 'Inactive',
        'Ativo': 'Active',
        'Hostname': 'Hostname',
        'IP Address': 'IP Address',
        'Sistema Operacional': 'Operating System',
        'Kernel': 'Kernel',
        'Arch': 'Architecture',
        'Processador': 'Processor',
        'Núcleos': 'Cores',
        'Memória (GB)': 'Memory (GB)',
        'Status': 'Status',
        'Última Atividade': 'Last Activity',
        'resultado(s) encontrado(s)': 'result(s) found',
        'Nenhum resultado encontrado': 'No results found',
        'Tente ajustar sua pesquisa': 'Try adjusting your search',
        'Pesquisar Máquinas': 'Search Machines',
        'Pesquisar': 'Search',
        'Pesquisar por hostname, SO ou processador...': 'Search by hostname, OS or processor...',

        
        # Machine Details
        'Informações Básicas': 'Informações Básicas',
        
        # Configurações
        'Exportar PDF': 'Export PDF',
        'Sincronizar com Wazuh': 'Sync with Wazuh',
        'Notificações': 'Notifications',
        'Segurança': 'Security',
        'Autenticação em Duas Etapas': 'Two-Factor Authentication',
        'Configurar MFA': 'Configure MFA',
        'Gerar PDF': 'Generate PDF',
        'Cancelar': 'Cancel',
        'Incluir detalhes completos': 'Include full details',
        'Sincronize os dados do inventário com o Wazuh Manager para manter todas as informações atualizadas.': 'Synchronize inventory data with the Wazuh Manager to keep all information up to date.',
        'Configure suas preferências de notificação para receber alertas importantes.': 'Set your notification preferences to receive important alerts.',
        'Exportar Relatório PDF': 'Exportar Relatório PDF',
        'Exportar um relatório completo em PDF com todas as informações do sistema': 'Export a complete PDF report with all system information',
        'Escolha as opções para o relatório:': 'Choose the options for the report:',
        'Configure a autenticação de dois fatores (MFA) para aumentar a segurança.': 'Set up two-factor authentication (MFA) to increase security.',
        'MFA está ': 'MFA is',
        'habilitada': 'enable',
        'desabilitada': 'disable',
        'Desabilitar MFA': 'Enable MFA',
        'Código de 6 dígitos': '6-digit code',
        'Desabilitar MFA': 'Disable MFA',
        'Habilitar MFA': 'Enable MFA',
        'Secret': 'Secret',
        'Verificar': 'Verify',
        'Cancelar': 'Cancel',
        
        # Detalhes da máquina
        'Informações Básicas': 'Basic Information',
        'Hardware': 'Hardware',
        'Network interfaces': 'Network Interfaces',
        'Network ports': 'Network Ports',
        'Network settings': 'Network Settings',
        'Installed Packages': 'Installed Packages',
        'Running Processes': 'Running Processes',
        'Interface': 'Interface',
        'MAC': 'MAC',
        'State': 'State',
        'MTU': 'MTU',
        'Type': 'Type',
        'Local port': 'Local Port',
        'Local IP': 'Local IP',
        'Process': 'Process',
        'PID': 'PID',
        'Address': 'Address',
        'Netmask': 'Netmask',
        'Proto': 'Protocol',
        'Broadcast': 'Broadcast',
        'Name': 'Name',
        'Version': 'Version',
        'Description': 'Description',
        'Architecture': 'Architecture',
        'Format': 'Format',
        'User': 'User',
        'Command': 'Command',
    },
    ##############
    ## ESPANHOL ##
    ##############
    'es': {
        # Menu principal
        'Dashboard': 'Panel',
        'Painel': 'Máquinas',
        'Pesquisa': 'Búsqueda',
        'Configurações': 'Configuración',
        'Sair': 'Salir',
        
        # Login
        'Usuário': 'Usuario',
        'Senha': 'Contraseña',
        'Entrar': 'Entrar',
        'Credenciais inválidas': 'Credenciales inválidas',
        'Preencha todos os campos': 'Complete todos los campos',
        'Código MFA inválido': 'Código MFA inválido',
        'Coleta de dados iniciada, aguarde alguns minutos.': 'Recolección de datos iniciada, espere unos minutos.',
        
        
        
        #Dashboard
        'Total de Máquinas': 'Total de Maquinas',
        'Ativas': 'Activas',
        'Inativas': 'Inactivas',
        'Atividade': 'Actividad',
        'Processos': 'Procesos',
        'Nenhum dado disponível': 'Ningún dato disponible',
        'Carregando dados...': 'Cargando datos...',
        'Sistemas Operacionais': 'Sistemas Operativos',
        'Processadores': 'Procesadores',
        'Memória RAM': 'Memoria RAM',
        'Portas de Rede Mais Comuns': 'Puertos de Red Mas Comunes',
        'Processos Mais Comuns': 'Procesos Más Comunes',
        'Distribuição por Grupos': 'Distribución por grupos',
        'Máquinas Recentemente Sincronizadas': 'Máquinas Sincronizadas recientemente',
        'Ver todas': 'Ver todo',
        'Sistema': 'Sistema',
        'Evolução Temporal - Máquinas Ativas e Inativas': 'Evolución temporal: máquinas activas e inactivas',
        
        
        # Painel de máquinas
        'Máquinas': 'Máquinas',
        'Detalhes': 'Detalles',
        'Voltar': 'Volver',
        'Hostname': 'Hostname',
        'IP Address': 'Dirección IP',
        'Inativo': 'Inactivo',
        'Ativo': 'Activo',
        'Sistema Operacional': 'Sistema Operativo',
        'Kernel': 'Kernel',
        'Arch': 'Arquitectura',
        'Processador': 'Procesador',
        'Núcleos': 'Núcleos',
        'Memória (GB)': 'Memoria (GB)',
        'Status': 'Estado',
        'Última Atividade': 'Última Actividad',
        'resultado(s) encontrado(s)': 'resultado(s) encontrado(s)',
        'Nenhum resultado encontrado': 'No se encontraron resultados',
        'Tente ajustar sua pesquisa': 'Intente ajustar su búsqueda',
        'Pesquisar Máquinas': 'Buscar máquinas',
        'Pesquisar': 'Buscar',
        'Pesquisar por hostname, SO ou processador...': 'Buscar por hostname, SO o procesador...',
        
        # Configurações
        'Exportar PDF': 'Exportar PDF',
        'Sincronizar com Wazuh': 'Sincronizar con Wazuh',
        'Notificações': 'Notificaciones',
        'Segurança': 'Seguridad',
        'Autenticação em Duas Etapas': 'Autenticación en Dos Pasos',
        'Configurar MFA': 'Configurar MFA',
        'Gerar PDF': 'Generar PDF',
        'Cancelar': 'Cancelar',
        'Incluir detalhes completos': 'Incluir detalles completos',
        'Sincronize os dados do inventário': 'Sincronice los datos del inventario',
        'Sincronize os dados do inventário com o Wazuh Manager para manter todas as informações atualizadas.': 'Sincronice sus datos de inventario con Wazuh Manager para mantener toda la información actualizada.',
        'Configure suas preferências de notificação para receber alertas importantes.': 'Configure sus preferencias de notificación para recibir alertas importantes.',
        'Exportar Relatório':'Exportar Relatório',
        'Exportar Relatório PDF': 'Exportar Relatório PDF',
        'Exportar um relatório completo em PDF com todas as informações do sistema': 'Exportar un informe PDF completo con toda la información del sistema',
        'Escolha as opções para o relatório:': 'Elija las opciones para el informe:',
        'Configure a autenticação de dois fatores (MFA) para aumentar a segurança.': 'Configure la autenticación de dos factores (MFA) para aumentar la seguridad.',
        'MFA está ': 'MFA es',
        'habilitada': 'activado',
        'desabilitada': 'desactivado',
        'Desabilitar MFA': 'Desactivar MFA',
        'Código de 6 dígitos': 'Código de 6 dígitos',
        'Desabilitar MFA': 'Deshabilitar MFA',
        'Habilitar MFA': 'Habilitar MFA',
        'Secret': 'Secreto',
        'Verificar': 'Verificar',
        'Cancelar': 'Cancelar',
        
        # Detalhes da máquina
        'Informações Básicas': 'Información Básica',
        'Hardware': 'Hardware',
        'Network interfaces': 'Interfaces de Red',
        'Network ports': 'Puertos de Red',
        'Network settings': 'Configuraciones de Red',
        'Installed Packages': 'Paquetes Instalados',
        'Running Processes': 'Procesos en Ejecución',
        'Interface': 'Interfaz',
        'MAC': 'MAC',
        'State': 'Estado',
        'MTU': 'MTU',
        'Type': 'Tipo',
        'Local port': 'Puerto Local',
        'Local IP': 'IP Local',
        'Process': 'Proceso',
        'PID': 'PID',
        'Address': 'Dirección',
        'Netmask': 'Máscara de Red',
        'Proto': 'Protocolo',
        'Broadcast': 'Broadcast',
        'Name': 'Nombre',
        'Version': 'Versión',
        'Description': 'Descripción',
        'Architecture': 'Arquitectura',
        'Format': 'Formato',
        'User': 'Usuario',
        'Command': 'Comando',
    },
    #############
    ## HINDI   ##
    #############
    'hi': {
        # Menu principal
        'Dashboard': 'डैशबोर्ड',
        'Painel': 'मशीनें',
        'Pesquisa': 'खोज',
        'Configurações': 'सेटिंग्स',
        'Sair': 'लॉगआउट',
        
        # Login
        'Usuário': 'उपयोगकर्ता नाम',
        'Senha': 'पासवर्ड',
        'Entrar': 'लॉगिन',
        'Credenciais inválidas': 'अमान्य क्रेडेंशियल्स',
        'Preencha todos os campos': 'कृपया सभी फ़ील्ड भरें',
        'Código MFA inválido': 'अमान्य MFA कोड',
        'Coleta de dados iniciada, aguarde alguns minutos.': 'डेटा संग्रह शुरू हो गया है, कृपया कुछ मिनट प्रतीक्षा करें।',
        
        # Dashboard
        'Total de Máquinas': 'कुल मशीनें',
        'Ativas': 'सक्रिय',
        'Inativas': 'निष्क्रिय',
        'Atividade': 'गतिविधि',
        'Processos': 'प्रोसेस',
        'Inativo': 'निष्क्रिय',
        'Ativo': 'सक्रिय',
        'Nenhum dado disponível': 'कोई डेटा उपलब्ध नहीं',
        'Carregando dados...': 'डेटा लोड हो रहा है...',
        'Sistemas Operacionais': 'ऑपरेटिंग सिस्टम',
        'Processadores': 'प्रोसेसर',
        'Memória RAM': 'रैम मेमोरी',
        'Portas de Rede Mais Comuns': 'सबसे आम नेटवर्क पोर्ट',
        'Processos Mais Comuns': 'सबसे आम प्रोसेस',
        'Distribuição por Grupos': 'ग्रुप द्वारा वितरण',
        'Máquinas Recentemente Sincronizadas': 'हाल ही में सिंक की गई मशीनें',
        'Ver todas': 'सभी देखें',
        'Sistema': 'सिस्टम',
        'Evolução Temporal - Máquinas Ativas e Inativas': 'समय विकास - सक्रिय और निष्क्रिय मशीनें',
        
        # Painel de máquinas
        'Máquinas': 'मशीनें',
        'Detalhes': 'विवरण',
        'Voltar': 'वापस',
        'Hostname': 'होस्टनेम',
        'IP Address': 'IP पता',
        'Sistema Operacional': 'ऑपरेटिंग सिस्टम',
        'Kernel': 'कर्नेल',
        'Arch': 'आर्किटेक्चर',
        'Processador': 'प्रोसेसर',
        'Núcleos': 'कोर',
        'Memória (GB)': 'मेमोरी (GB)',
        'Status': 'स्थिति',
        'Última Atividade': 'अंतिम गतिविधि',
        'resultado(s) encontrado(s)': 'परिणाम मिला',
        'Nenhum resultado encontrado': 'कोई परिणाम नहीं मिला',
        'Tente ajustar sua pesquisa': 'अपनी खोज समायोजित करें',
        'Pesquisar Máquinas': 'मशीनें खोजें',
        'Pesquisar': 'खोजें',
        'Pesquisar por hostname, SO ou processador...': 'होस्टनेम, OS या प्रोसेसर द्वारा खोजें...',
        
        # Machine Details
        'Informações Básicas': 'मूल जानकारी',
        
        # Configurações
        'Exportar PDF': 'PDF निर्यात करें',
        'Sincronizar com Wazuh': 'Wazuh के साथ सिंक करें',
        'Notificações': 'सूचनाएं',
        'Segurança': 'सुरक्षा',
        'Autenticação em Duas Etapas': 'दो-कारक प्रमाणीकरण',
        'Configurar MFA': 'MFA कॉन्फ़िगर करें',
        'Gerar PDF': 'PDF बनाएं',
        'Cancelar': 'रद्द करें',
        'Incluir detalhes completos': 'पूर्ण विवरण शामिल करें',
        'SYNC com Wazuh': 'Wazuh के साथ सिंक करें',
        'Sincronize os dados do inventário com o Wazuh Manager para manter todas as informações atualizadas.': 'सभी जानकारी अपडेट रखने के लिए इन्वेंट्री डेटा को Wazuh Manager के साथ सिंक करें।',
        'Configure suas preferências de notificação para receber alertas importantes.': 'महत्वपूर्ण अलर्ट प्राप्त करने के लिए अपनी अधिसूचना प्राथमिकताएं कॉन्फ़िगर करें।',
        'Exportar Relatório': 'निर्यात रिपोर्ट',
        'Exportar Relatório PDF': 'रिपोर्ट को पीडीएफ में एक्सपोर्ट करें।',
        'Exportar um relatório completo em PDF com todas as informações do sistema': 'सिस्टम जानकारी के साथ पूर्ण PDF रिपोर्ट निर्यात करें',
        'Escolha as opções para o relatório:': 'रिपोर्ट के लिए विकल्प चुनें:',
        'Configure a autenticação de dois fatores (MFA) para aumentar a segurança.': 'सुरक्षा बढ़ाने के लिए MFA सेटअप करें।',
        'MFA está ': 'MFA यह है',
        'habilitada': 'सक्रिय',
        'desabilitada': 'अक्षम',
        'Desabilitar MFA': 'MFA निष्क्रिय करें',
        'Código de 6 dígitos': '6 डिजिट कोड:',
        'Habilitar MFA': 'MFA सक्रिय करें',
        'Secret': 'गुप्त कोड',
        'Verificar': 'सत्यापित करें',
        'Cancelar': 'रद्द करें',
        
        # Detalhes da máquina
        'Hardware': 'हार्डवेयर',
        'Network interfaces': 'नेटवर्क इंटरफेस',
        'Network ports': 'नेटवर्क पोर्ट',
        'Network settings': 'नेटवर्क सेटिंग्स',
        'Installed Packages': 'इंस्टॉल किए गए पैकेज',
        'Running Processes': 'चल रहे प्रोसेस',
        'Interface': 'इंटरफेस',
        'MAC': 'MAC',
        'State': 'स्थिति',
        'MTU': 'MTU',
        'Type': 'प्रकार',
        'Local port': 'स्थानीय पोर्ट',
        'Local IP': 'स्थानीय IP',
        'Process': 'प्रोसेस',
        'PID': 'PID',
        'Address': 'पता',
        'Netmask': 'नेटमास्क',
        'Proto': 'प्रोटोकॉल',
        'Broadcast': 'ब्रॉडकास्ट',
        'Name': 'नाम',
        'Version': 'संस्करण',
        'Description': 'विवरण',
        'Architecture': 'आर्किटेक्चर',
        'Format': 'फॉर्मेट',
        'User': 'उपयोगकर्ता',
        'Command': 'कमान्ड',
    }
    
}