LANGUAGES = {
    ####################
    ## PORTUGUES (BR) ##
    ####################
    'pt': {
        # Menu principal
        'Dashboard': 'Dashboard',
        'Painel': 'Painel',
        'Pesquisa': 'Pesquisa',
        'Configurações': 'Configurações',
        'Sair': 'Sair',
        
        # Login
        'Usuário': 'Usuário',
        'Senha': 'Senha',
        'Entrar': 'Entrar',
        'Credenciais inválidas': 'Credenciais inválidas',
        'Preencha todos os campos': 'Preencha todos os campos',
        'Código MFA inválido': 'Código MFA inválido',
        'Coleta de dados iniciada, aguarde alguns minutos.': 'Coleta de dados iniciada, aguarde alguns minutos.',
        'Gestão de Usuários': 'Gestão de Usuários',
        'Máquinas Legadas': 'Máquinas Legadas',
        'Gerenciar registros obsoletos': 'Gerenciar registros obsoletos',
        'Ações': 'Ações',
        'Última Sincronização': 'Última Sincronização',
        'Legado': 'Legado',
        'Pesquisar por hostname, data...': 'Pesquisar por hostname, data...',
        'Excluir': 'Excluir',
        'Função': 'Função',
        'Nenhuma máquina legada encontrada. Seu inventário está 100% sincronizado!': 'Nenhuma máquina legada encontrada. Seu inventário está 100% sincronizado!',
        'Agent ID': 'Agent ID',
        'Grupos': 'Grupos',
        'Placa Mãe': 'Placa Mãe',
        'Voltar ao Painel': 'Voltar ao Painel',
        'Máquinas Ativas': 'Máquinas Ativas',
        'Máquinas Inativas': 'Máquinas Inativas',
        'Nome': 'Nome',
        
        
        # Novas Modais de Configuração
        'Alterar Senha': 'Alterar Senha',
        'Alterar Minha Senha': 'Alterar Minha Senha',
        'Senha Atual': 'Senha Atual',
        'Nova Senha': 'Nova Senha',
        'Confirmar Nova Senha': 'Confirmar Nova Senha',
        'Digite sua senha atual': 'Digite sua senha atual',
        'Digite a nova senha': 'Digite a nova senha',
        'Repita a nova senha': 'Repita a nova senha',
        'As senhas não coincidem': 'As senhas não coincidem',
        'Salvar Alterações': 'Salvar Alterações',
        'Mantenha sua conta segura alterando sua senha periodicamente.': 'Mantenha sua conta segura alterando sua senha periodicamente.',
        'Adicione, remova ou edite as permissões dos usuários do sistema.': 'Adicione, remova ou edite as permissões dos usuários do sistema.',
        'Gerencie e exclua registros antigos de máquinas que não estão mais sincronizadas.': 'Gerencie e exclua registros antigos de máquinas que não estão mais sincronizadas.',
        'Ver Legado': 'Ver Legado',
        'Gerenciar Usuários': 'Gerenciar Usuários',
        'Lista de usuários ativos no sistema.': 'Lista de usuários ativos no sistema.',
        'Remover': 'Remover',
        'Deseja realmente remover este usuário?': 'Deseja realmente remover este usuário?',
        'Em breve': 'Em breve',
        
        #Dashboard
        'Total de Máquinas': 'Total de Máquinas',
        'Ativas': 'Ativas',
        'Inativas': 'Inativas',
        'Atividade': 'Atividade',
        'Processos': 'Processos',
        'Nenhum dado disponível': 'Nenhum dado disponível',
        'Carregando dados...': 'Carregando dados...',
        'Sistemas Operacionais': 'Sistemas Operacionais',
        'Processadores': 'Processadores',
        'Memória RAM': 'Memória RAM',
        'Portas de Rede Mais Comuns': 'Portas de Rede Mais Comuns',
        'Processos Mais Comuns': 'Processos Mais Comuns',
        'Distribuição por Grupos': 'Distribuição por Grupos',
        'Máquinas Recentemente Sincronizadas': 'Máquinas Recentemente Sincronizadas',
        'Ver todas': 'Ver todas',
        'Sistema': 'Sistema',
        'Evolução Temporal - Máquinas Ativas e Inativas': 'Evolução Temporal - Máquinas Ativas e Inativas',
        
        # Painel de máquinas
        'Máquinas': 'Máquinas',
        'Detalhes': 'Detalhes',
        'Voltar': 'Voltar',
        'Hostname': 'Hostname',
        'IP Address': 'Endereço IP',
        'Inativo': 'Inativo',
        'Ativo': 'Ativo',
        'Sistema Operacional': 'Sistema Operacional',
        'Kernel': 'Kernel',
        'Arch': 'Arquitetura',
        'Processador': 'Processador',
        'Núcleos': 'Núcleos',
        'Memória (GB)': 'Memória (GB)',
        'Status': 'Status',
        'Última Atividade': 'Última Atividade',
        'resultado(s) encontrado(s)': 'resultado(s) encontrado(s)',
        'Nenhum resultado encontrado': 'Nenhum resultado encontrado',
        'Tente ajustar sua pesquisa': 'Tente ajustar sua pesquisa',
        'Pesquisar Máquinas': 'Pesquisar Máquinas',
        'Pesquisar': 'Pesquisar',
        'Pesquisar por hostname, SO ou processador...': 'Pesquisar por hostname, SO ou processador...',
        
        
        # Machine Details
        'Informações Básicas': 'Informações Básicas',
        
        # Configurações
        'Exportar PDF': 'Exportar PDF',
        'Sincronizar com Wazuh': 'Sincronizar com Wazuh',
        'Notificações': 'Notificações',
        'Segurança': 'Segurança',
        'Autenticação em Duas Etapas': 'Autenticação em Duas Etapas',
        'Configurar MFA': 'Configurar MFA',
        'Gerar PDF': 'Gerar PDF',
        'Cancelar': 'Cancelar',
        'Incluir detalhes completos': 'Incluir detalhes completos',
        'Sincronize os dados do inventário com o Wazuh Manager para manter todas as informações atualizadas.': 'Sincronize os dados do inventário com o Wazuh Manager para manter todas as informações atualizadas.',
        'Configure suas preferências de notificação para receber alertas importantes.': 'Configure suas preferências de notificação para receber alertas importantes.',
        'Exportar Relatório PDF': 'Exportar Relatório PDF',
        'Exportar um relatório completo em PDF com todas as informações do sistema': 'Exportar um relatório completo em PDF com todas as informações do sistema',
        'Escolha as opções para o relatório:': 'Escolha as opções para o relatório:',
        'Exportar Agora': 'Exportar Agora',
        'Configure a autenticação de dois fatores (MFA) para aumentar a segurança.': 'Configure a autenticação de dois fatores (MFA) para aumentar a segurança.',
        'MFA está ': 'MFA está',
        'habilitada': 'habilitada',
        'desabilitada': 'desabilitada',
        'Desabilitar MFA': 'Desabilitar MFA',
        'Código de 6 dígitos': 'Código de 6 dígitos',
        'Desabilitar MFA': 'Desabilitar MFA',
        'Habilitar MFA': 'Habilitar MFA',
        'Secret': 'Chave Secreta',
        'Verificar': 'Verificar',
        'Cancelar': 'Cancelar',
        'Novo Usuário': 'Novo Usuário',
        'Nome de Usuário': 'Nome de Usuário',
        'Confirmar Senha': 'Confirmar Senha',
        'Criar Usuário': 'Criar Usuário',
        'Periodicidade de Sincronização': 'Periodicidade de Sincronização',
        'Selecione o intervalo entre as coletas automáticas de dados.': 'Selecione o intervalo entre as coletas automáticas de dados.',
        'Intervalo atual': 'Intervalo atual',
        'Sincronizar Agora': 'Sincronizar Agora',
        'Salvar Configuração': 'Salvar Configuração',
        'Gerar Relatório': 'Gerar Relatório',
        'Selecione os parâmetros para a exportação do relatório detalhado em formato PDF.': 'Selecione os parâmetros para a exportação do relatório detalhado em formato PDF.',
        'Incluir detalhes técnicos completos': 'Incluir detalhes técnicos completos',
        'Configure a frequência com que o sistema coleta dados do Wazuh API.': 'Configure a frequência com que o sistema coleta dados do Wazuh API.',
        'SYNC com Wazuh': 'SYNC com Wazuh',
        'Configurar Sync': 'Configurar Sync',
        
        
        
        # Detalhes da máquina
        'Informações Básicas': 'Informações Básicas',
        'Hardware': 'Hardware',
        'Network interfaces': 'Interfaces de Rede',
        'Network ports': 'Portas de Rede',
        'Network settings': 'Configurações de Rede',
        'Installed Packages': 'Pacotes Instalados',
        'Running Processes': 'Processos em Execução',
        'Interface': 'Interface',
        'MAC': 'MAC',
        'State': 'Estado',
        'MTU': 'MTU',
        'Type': 'Tipo',
        'Local port': 'Porta Local',
        'Local IP': 'IP Local',
        'Process': 'Processo',
        'PID': 'PID',
        'Address': 'Endereço',
        'Netmask': 'Máscara de Rede',
        'Proto': 'Protocolo',
        'Broadcast': 'Broadcast',
        'Name': 'Nome',
        'Version': 'Versão',
        'Description': 'Descrição',
        'Architecture': 'Arquitetura',
        'Format': 'Formato',
        'User': 'Usuário',
        'Command': 'Comando',
        
    },
    #############
    ## ENGLISH ##
    #############
    'en': {
        # Menu principal
        'Dashboard': 'Dashboard',
        'Painel': 'Machines',
        'Pesquisa': 'Search',
        'Configurações': 'Settings',
        'Sair': 'Logout',
        
        # Login
        'Usuário': 'Username',
        'Senha': 'Password',
        'Entrar': 'Login',
        'Credenciais inválidas': 'Invalid credentials',
        'Preencha todos os campos': 'Please fill all fields',
        'Código MFA inválido': 'Invalid MFA code',
        'Coleta de dados iniciada, aguarde alguns minutos.': 'Data collection started, please wait a few minutes.',
        'Gestão de Usuários': 'User Management',
        'Máquinas Legadas': 'Legacy Machines',
        'Gerenciar registros obsoletos': 'Manage obsolete records',
        'Ações': 'Actions',
        'Última Sincronização': 'Last Synchronization',
        'Legado': 'Legacy',
        'Pesquisar por hostname, data...': 'Search by hostname, date...',
        'Excluir': 'Delete',
        'Função': 'Role',
        'Nenhuma máquina legada encontrada. Seu inventário está 100% sincronizado!': 'No legacy machines found. Your inventory is 100% synchronized!',
        'Agent ID': 'Agent ID',
        'Grupos': 'Groups',
        'Placa Mãe': 'Motherboard',
        'Voltar ao Painel': 'Back to Dashboard',
        'Máquinas Ativas': 'Active Machines',
        'Máquinas Inativas': 'Inactive Machines',
        'Nome': 'Name',
        
        
        # Novas Modais de Configuração
        'Alterar Senha': 'Change Password',
        'Alterar Minha Senha': 'Change My Password',
        'Senha Atual': 'Current Password',
        'Nova Senha': 'New Password',
        'Confirmar Nova Senha': 'Confirm New Password',
        'Digite sua senha atual': 'Enter your current password',
        'Digite a nova senha': 'Enter the new password',
        'Repita a nova senha': 'Repeat the new password',
        'As senhas não coincidem': 'Passwords do not match',
        'Salvar Alterações': 'Save Changes',
        'Mantenha sua conta segura alterando sua senha periodicamente.': 'Keep your account secure by changing your password periodically.',
        'Adicione, remova ou edite as permissões dos usuários do sistema.': 'Add, remove or edit the permissions of the system users.',
        'Gerencie e exclua registros antigos de máquinas que não estão mais sincronizadas.': 'Manage and delete old records of machines that are no longer synchronized.',
        'Ver Legado': 'View Legacy',
        'Gerenciar Usuários': 'Manage Users',
        'Lista de usuários ativos no sistema.': 'List of active users in the system.',
        'Remover': 'Remove',
        'Deseja realmente remover este usuário?': 'Do you really want to remove this user?',
        'Em breve': 'Coming soon',
        
        #Dashboard
        'Total de Máquinas': 'Total of Machines',
        'Ativas': 'Active',
        'Inativas': 'Inactive',
        'Atividade': 'Activity',
        'Processos': 'Processes',
        'Nenhum dado disponível': 'No data available',
        'Carregando dados...': 'Loading data...',
        'Sistemas Operacionais': 'Operating Systems',
        'Processadores': 'Processors',
        'Memória RAM': 'RAM Memory',
        'Portas de Rede Mais Comuns': 'Most Common Network Ports',
        'Processos Mais Comuns': 'Most Common Processes',
        'Distribuição por Grupos': 'Distribution by Groups',
        'Máquinas Recentemente Sincronizadas': 'Recently Sync Machines',
        'Ver todas': 'See all',
        'Sistema': 'System',
        'Evolução Temporal - Máquinas Ativas e Inativas': 'Temporal Evolution - Active and Inactive Machines',
        
        # Painel de máquinas
        'Máquinas': 'Machines',
        'Detalhes': 'Details',
        'Voltar': 'Back',
        'Inativo': 'Inactive',
        'Ativo': 'Active',
        'Hostname': 'Hostname',
        'IP Address': 'IP Address',
        'Sistema Operacional': 'Operating System',
        'Kernel': 'Kernel',
        'Arch': 'Architecture',
        'Processador': 'Processor',
        'Núcleos': 'Cores',
        'Memória (GB)': 'Memory (GB)',
        'Status': 'Status',
        'Última Atividade': 'Last Activity',
        'resultado(s) encontrado(s)': 'result(s) found',
        'Nenhum resultado encontrado': 'No results found',
        'Tente ajustar sua pesquisa': 'Try adjusting your search',
        'Pesquisar Máquinas': 'Search Machines',
        'Pesquisar': 'Search',
        'Pesquisar por hostname, SO ou processador...': 'Search by hostname, OS or processor...',

        
        # Machine Details
        'Informações Básicas': 'Informações Básicas',
        
        # Configurações
        'Exportar PDF': 'Export PDF',
        'Sincronizar com Wazuh': 'Sync with Wazuh',
        'Notificações': 'Notifications',
        'Segurança': 'Security',
        'Autenticação em Duas Etapas': 'Two-Factor Authentication',
        'Configurar MFA': 'Configure MFA',
        'Gerar PDF': 'Generate PDF',
        'Cancelar': 'Cancel',
        'Incluir detalhes completos': 'Include full details',
        'Sincronize os dados do inventário com o Wazuh Manager para manter todas as informações atualizadas.': 'Synchronize inventory data with the Wazuh Manager to keep all information up to date.',
        'Configure suas preferências de notificação para receber alertas importantes.': 'Set your notification preferences to receive important alerts.',
        'Exportar Relatório PDF': 'Exportar Relatório PDF',
        'Exportar um relatório completo em PDF com todas as informações do sistema': 'Export a complete PDF report with all system information',
        'Escolha as opções para o relatório:': 'Choose the options for the report:',
        'Exportar Agora': 'Export Now',
        'Configure a autenticação de dois fatores (MFA) para aumentar a segurança.': 'Set up two-factor authentication (MFA) to increase security.',
        'MFA está ': 'MFA is',
        'habilitada': 'enable',
        'desabilitada': 'disable',
        'Desabilitar MFA': 'Enable MFA',
        'Código de 6 dígitos': '6-digit code',
        'Desabilitar MFA': 'Disable MFA',
        'Habilitar MFA': 'Enable MFA',
        'Secret': 'Secret',
        'Verificar': 'Verify',
        'Cancelar': 'Cancel',
        'Novo Usuário': 'New User',
        'Nome de Usuário': 'Username',
        'Confirmar Senha': 'Confirm Password',
        'Criar Usuário': 'Create User',
        'Periodicidade de Sincronização': 'Synchronization Frequency',
        'Selecione o intervalo entre as coletas automáticas de dados.': 'Select the interval between automatic data collections.',
        'Intervalo atual': 'Current interval',
        'Sincronizar Agora': 'Sync Now',
        'Salvar Configuração': 'Save Settings',
        'Gerar Relatório': 'Generate Report',
        'Selecione os parâmetros para a exportação do relatório detalhado em formato PDF.': 'Select parameters for exporting the detailed PDF report.',
        'Incluir detalhes técnicos completos': 'Include full technical details',
        'Configure a frequência com que o sistema coleta dados do Wazuh API.': 'Configure how often the system collects data from the Wazuh API.',
        'SYNC com Wazuh': 'SYNC with Wazuh',
        'Configurar Sync': 'Configure Sync',
        
        
        # Detalhes da máquina
        'Informações Básicas': 'Basic Information',
        'Hardware': 'Hardware',
        'Network interfaces': 'Network Interfaces',
        'Network ports': 'Network Ports',
        'Network settings': 'Network Settings',
        'Installed Packages': 'Installed Packages',
        'Running Processes': 'Running Processes',
        'Interface': 'Interface',
        'MAC': 'MAC',
        'State': 'State',
        'MTU': 'MTU',
        'Type': 'Type',
        'Local port': 'Local Port',
        'Local IP': 'Local IP',
        'Process': 'Process',
        'PID': 'PID',
        'Address': 'Address',
        'Netmask': 'Netmask',
        'Proto': 'Protocol',
        'Broadcast': 'Broadcast',
        'Name': 'Name',
        'Version': 'Version',
        'Description': 'Description',
        'Architecture': 'Architecture',
        'Format': 'Format',
        'User': 'User',
        'Command': 'Command',
    },
    ##############
    ## ESPANHOL ##
    ##############
    'es': {
        # Menu principal
        'Dashboard': 'Panel',
        'Painel': 'Máquinas',
        'Pesquisa': 'Búsqueda',
        'Configurações': 'Configuración',
        'Sair': 'Salir',
        
        # Login
        'Usuário': 'Usuario',
        'Senha': 'Contraseña',
        'Entrar': 'Entrar',
        'Credenciais inválidas': 'Credenciales inválidas',
        'Preencha todos os campos': 'Complete todos los campos',
        'Código MFA inválido': 'Código MFA inválido',
        'Coleta de dados iniciada, aguarde alguns minutos.': 'Recolección de datos iniciada, espere unos minutos.',
        'Gestão de Usuários': 'Gestión de Usuarios',
        'Máquinas Legadas': 'Máquinas Legadas',
        'Gerenciar registros obsoletos': 'Gestionar registros obsoletos',
        'Ações': 'Acciones',
        'Última Sincronização': 'Última Sincronización',
        'Legado': 'Legado',
        'Pesquisar por hostname, data...': 'Buscar por hostname, fecha...',
        'Excluir': 'Eliminar',
        'Função': 'Rol',
        'Nenhuma máquina legada encontrada. Seu inventário está 100% sincronizado!': 'No se encontraron máquinas legadas. ¡Su inventario está 100% sincronizado!',
        'Agent ID': 'ID de Agente',
        'Grupos': 'Grupos',
        'Placa Mãe': 'Placa Base',
        'Voltar ao Painel': 'Volver al Panel',
        'Máquinas Ativas': 'Máquinas Activas',
        'Máquinas Inativas': 'Máquinas Inactivas',
        'Nome': 'Nombre',
        
        
        # Novas Modais de Configuração
        'Alterar Senha': 'Cambiar Contraseña',
        'Alterar Minha Senha': 'Cambiar Mi Contraseña',
        'Senha Atual': 'Contraseña Actual',
        'Nova Senha': 'Nueva Contraseña',
        'Confirmar Nova Senha': 'Confirmar Nueva Contraseña',
        'Digite sua senha atual': 'Ingrese su contraseña actual',
        'Digite a nova senha': 'Ingrese la nueva contraseña',
        'Repita a nova senha': 'Repita la nueva contraseña',
        'As senhas não coincidem': 'Las contraseñas no coinciden',
        'Salvar Alterações': 'Guardar Cambios',
        'Mantenha sua conta segura alterando sua senha periodicamente.': 'Mantenga su cuenta segura cambiando su contraseña periódicamente.',
        'Adicione, remova ou edite as permissões dos usuários do sistema.': 'Agregue, elimine o edite los permisos de los usuarios del sistema.',
        'Gerencie e exclua registros antigos de máquinas que não estão mais sincronizadas.': 'Administre y elimine registros antiguos de máquinas que ya no están sincronizadas.',
        'Ver Legado': 'Ver Legado',
        'Gerenciar Usuários': 'Administrar Usuarios',
        'Lista de usuários ativos no sistema.': 'Lista de usuarios activos en el sistema.',
        'Remover': 'Eliminar',
        'Deseja realmente remover este usuário?': '¿Realmente desea eliminar este usuario?',
        'Em breve': 'Próximamente',
        
        
        
        #Dashboard
        'Total de Máquinas': 'Total de Maquinas',
        'Ativas': 'Activas',
        'Inativas': 'Inactivas',
        'Atividade': 'Actividad',
        'Processos': 'Procesos',
        'Nenhum dado disponível': 'Ningún dato disponible',
        'Carregando dados...': 'Cargando datos...',
        'Sistemas Operacionais': 'Sistemas Operativos',
        'Processadores': 'Procesadores',
        'Memória RAM': 'Memoria RAM',
        'Portas de Rede Mais Comuns': 'Puertos de Red Mas Comunes',
        'Processos Mais Comuns': 'Procesos Más Comunes',
        'Distribuição por Grupos': 'Distribución por grupos',
        'Máquinas Recentemente Sincronizadas': 'Máquinas Sincronizadas recientemente',
        'Ver todas': 'Ver todo',
        'Sistema': 'Sistema',
        'Evolução Temporal - Máquinas Ativas e Inativas': 'Evolución temporal: máquinas activas e inactivas',
        
        
        # Painel de máquinas
        'Máquinas': 'Máquinas',
        'Detalhes': 'Detalles',
        'Voltar': 'Volver',
        'Hostname': 'Hostname',
        'IP Address': 'Dirección IP',
        'Inativo': 'Inactivo',
        'Ativo': 'Activo',
        'Sistema Operacional': 'Sistema Operativo',
        'Kernel': 'Kernel',
        'Arch': 'Arquitectura',
        'Processador': 'Procesador',
        'Núcleos': 'Núcleos',
        'Memória (GB)': 'Memoria (GB)',
        'Status': 'Estado',
        'Última Atividade': 'Última Actividad',
        'resultado(s) encontrado(s)': 'resultado(s) encontrado(s)',
        'Nenhum resultado encontrado': 'No se encontraron resultados',
        'Tente ajustar sua pesquisa': 'Intente ajustar su búsqueda',
        'Pesquisar Máquinas': 'Buscar máquinas',
        'Pesquisar': 'Buscar',
        'Pesquisar por hostname, SO ou processador...': 'Buscar por hostname, SO o procesador...',
        
        # Configurações
        'Exportar PDF': 'Exportar PDF',
        'Sincronizar com Wazuh': 'Sincronizar con Wazuh',
        'Notificações': 'Notificaciones',
        'Segurança': 'Seguridad',
        'Autenticação em Duas Etapas': 'Autenticación en Dos Pasos',
        'Configurar MFA': 'Configurar MFA',
        'Gerar PDF': 'Generar PDF',
        'Cancelar': 'Cancelar',
        'Incluir detalhes completos': 'Incluir detalles completos',
        'Sincronize os dados do inventário': 'Sincronice los datos del inventario',
        'Sincronize os dados do inventário com o Wazuh Manager para manter todas as informações atualizadas.': 'Sincronice sus datos de inventario con Wazuh Manager para mantener toda la información actualizada.',
        'Configure suas preferências de notificação para receber alertas importantes.': 'Configure sus preferencias de notificación para recibir alertas importantes.',
        'Exportar Relatório':'Exportar Relatório',
        'Exportar Relatório PDF': 'Exportar Relatório PDF',
        'Exportar um relatório completo em PDF com todas as informações do sistema': 'Exportar un informe PDF completo con toda la información del sistema',
        'Escolha as opções para o relatório:': 'Elija las opciones para el informe:',
        'Exportar Agora': 'Exportar Ahora',
        'Configure a autenticação de dois fatores (MFA) para aumentar a segurança.': 'Configure la autenticación de dos factores (MFA) para aumentar la seguridad.',
        'MFA está ': 'MFA es',
        'habilitada': 'activado',
        'desabilitada': 'desactivado',
        'Desabilitar MFA': 'Desactivar MFA',
        'Código de 6 dígitos': 'Código de 6 dígitos',
        'Desabilitar MFA': 'Deshabilitar MFA',
        'Habilitar MFA': 'Habilitar MFA',
        'Secret': 'Secreto',
        'Verificar': 'Verificar',
        'Cancelar': 'Cancelar',
        'Novo Usuário': 'Nuevo Usuario',
        'Nome de Usuário': 'Nombre de Usuario',
        'Confirmar Senha': 'Confirmar Contraseña',
        'Criar Usuário': 'Crear Usuario',
        'Periodicidade de Sincronização': 'Frecuencia de Sincronización',
        'Selecione o intervalo entre as coletas automáticas de dados.': 'Seleccione el intervalo entre colecciones automáticas de datos.',
        'Intervalo atual': 'Intervalo actual',
        'Sincronizar Agora': 'Sincronizar Ahora',
        'Salvar Configuração': 'Guardar Configuración',
        'Gerar Relatório': 'Generar Informe',
        'Selecione os parâmetros para a exportação do relatório detalhado em formato PDF.': 'Seleccione los parámetros para exportar el informe en PDF.',
        'Incluir detalhes técnicos completos': 'Incluir detalles técnicos completos',
        'Configure a frequência com que o sistema coleta dados do Wazuh API.': 'Configure la frecuencia con la que el sistema recopila datos de la API de Wazuh.',
        'SYNC com Wazuh': 'SYNC con Wazuh',
        'Configurar Sync': 'Configurar Sync',
        
        
        # Detalhes da máquina
        'Informações Básicas': 'Información Básica',
        'Hardware': 'Hardware',
        'Network interfaces': 'Interfaces de Red',
        'Network ports': 'Puertos de Red',
        'Network settings': 'Configuraciones de Red',
        'Installed Packages': 'Paquetes Instalados',
        'Running Processes': 'Procesos en Ejecución',
        'Interface': 'Interfaz',
        'MAC': 'MAC',
        'State': 'Estado',
        'MTU': 'MTU',
        'Type': 'Tipo',
        'Local port': 'Puerto Local',
        'Local IP': 'IP Local',
        'Process': 'Proceso',
        'PID': 'PID',
        'Address': 'Dirección',
        'Netmask': 'Máscara de Red',
        'Proto': 'Protocolo',
        'Broadcast': 'Broadcast',
        'Name': 'Nombre',
        'Version': 'Versión',
        'Description': 'Descripción',
        'Architecture': 'Arquitectura',
        'Format': 'Formato',
        'User': 'Usuario',
        'Command': 'Comando',
    },

    #############
    ## HINDI   ##
    #############
    'hi': {
        # Menu principal
        'Dashboard': 'डैशबोर्ड',
        'Painel': 'मशीनें',
        'Pesquisa': 'खोज',
        'Configurações': 'सेटिंग्स',
        'Sair': 'लॉगआउट',
        
        # Login
        'Usuário': 'उपयोगकर्ता नाम',
        'Senha': 'पासवर्ड',
        'Entrar': 'लॉगिन',
        'Credenciais inválidas': 'अमान्य क्रेडेंशियल्स',
        'Preencha todos os campos': 'कृपया सभी फ़ील्ड भरें',
        'Código MFA inválido': 'अमान्य MFA कोड',
        'Coleta de dados iniciada, aguarde alguns minutos.': 'डेटा संग्रह शुरू हो गया है, कृपया कुछ मिनट प्रतीक्षा करें।',
        'Gestão de Usuários': 'उपयोगकर्ता प्रबंधन',
        'Máquinas Legadas': 'विरासत मशीनें',
        'Gerenciar registros obsoletos': 'पुराने रिकॉर्ड प्रबंधित करें',
        'Ações': 'कार्रवाई',
        'Última Sincronização': 'अंतिम सिंक्रोनाइज़ेशन',
        'Legado': 'विरासत',
        'Pesquisar por hostname, data...': 'होस्टनेम, तिथि द्वारा खोजें...',
        'Excluir': 'हटाएं',
        'Função': 'भूमिका',
        'Nenhuma máquina legada encontrada. Seu inventário está 100% sincronizado!': 'कोई विरासत मशीन नहीं मिली। आपकी इन्वेंट्री 100% सिंक है!',
        'Agent ID': 'एजेंट आईडी',
        'Grupos': 'समूह',
        'Placa Mãe': 'मदरबोर्ड',
        'Voltar ao Painel': 'डैशबोर्ड पर वापस जाएं',
        'Máquinas Ativas': 'सक्रिय मशीनें',
        'Máquinas Inativas': 'निष्क्रिय मशीनें',
        'Nome': 'नाम',
        
        
        # Novas Modais de Configuração
        'Alterar Senha': 'पासवर्ड बदलें',
        'Alterar Minha Senha': 'मेरा पासवर्ड बदलें',
        'Senha Atual': 'वर्तमान पासवर्ड',
        'Nova Senha': 'नया पासवर्ड',
        'Confirmar Nova Senha': 'नए पासवर्ड की पुष्टि करें',
        'Digite sua senha atual': 'अपना वर्तमान पासवर्ड दर्ज करें',
        'Digite a nova senha': 'नया पासवर्ड दर्ज करें',
        'Repita a nova senha': 'नया पासवर्ड दोहराएं',
        'As senhas não coincidem': 'पासवर्ड मेल नहीं खाते',
        'Salvar Alterações': 'परिवर्तन सहेजें',
        'Mantenha sua conta segura alterando sua senha periodicamente.': 'समय-समय पर पासवर्ड बदलकर अपना खाता सुरक्षित रखें।',
        'Adicione, remova ou edite as permissões dos usuários do sistema.': 'सिस्टम उपयोगकर्ताओं की अनुमतियां जोड़ें, हटाएं या संपादित करें।',
        'Gerencie e exclua registros antigos de máquinas que não estão mais sincronizadas.': 'पुरानी मशीनों के रिकॉर्ड प्रबंधित करें और हटाएं।',
        'Ver Legado': 'विरासत देखें',
        'Gerenciar Usuários': 'उपयोगकर्ता प्रबंधित करें',
        'Lista de usuários ativos no sistema.': 'सिस्टम में सक्रिय उपयोगकर्ताओं की सूची।',
        'Remover': 'हटाएं',
        'Deseja realmente remover este usuário?': 'क्या आप वाकई इस उपयोगकर्ता को हटाना चाहते हैं?',
        'Em breve': 'जल्द आ रहा है',
        
        #Dashboard
        'Total de Máquinas': 'कुल मशीनें',
        'Ativas': 'सक्रिय',
        'Inativas': 'निष्क्रिय',
        'Atividade': 'गतिविधि',
        'Processos': 'प्रोसेस',
        'Nenhum dado disponível': 'कोई डेटा उपलब्ध नहीं',
        'Carregando dados...': 'डेटा लोड हो रहा है...',
        'Sistemas Operacionais': 'ऑपरेटिंग सिस्टम',
        'Processadores': 'प्रोसेसर',
        'Memória RAM': 'रैम मेमोरी',
        'Portas de Rede Mais Comuns': 'सबसे सामान्य नेटवर्क पोर्ट',
        'Processos Mais Comuns': 'सबसे सामान्य प्रोसेस',
        'Distribuição por Grupos': 'समूह के अनुसार वितरण',
        'Máquinas Recentemente Sincronizadas': 'हाल ही में सिंक की गई मशीनें',
        'Ver todas': 'सभी देखें',
        'Sistema': 'सिस्टम',
        'Evolução Temporal - Máquinas Ativas e Inativas': 'समय के साथ सक्रिय और निष्क्रिय मशीनों का विकास',
        
        # Painel de máquinas
        'Máquinas': 'मशीनें',
        'Detalhes': 'विवरण',
        'Voltar': 'वापस',
        'Inativo': 'निष्क्रिय',
        'Ativo': 'सक्रिय',
        'Hostname': 'होस्टनेम',
        'IP Address': 'IP पता',
        'Sistema Operacional': 'ऑपरेटिंग सिस्टम',
        'Kernel': 'कर्नेल',
        'Arch': 'आर्किटेक्चर',
        'Processador': 'प्रोसेसर',
        'Núcleos': 'कोर',
        'Memória (GB)': 'मेमोरी (GB)',
        'Status': 'स्थिति',
        'Última Atividade': 'अंतिम गतिविधि',
        'resultado(s) encontrado(s)': 'परिणाम मिले',
        'Nenhum resultado encontrado': 'कोई परिणाम नहीं मिला',
        'Tente ajustar sua pesquisa': 'अपनी खोज समायोजित करें',
        'Pesquisar Máquinas': 'मशीन खोजें',
        'Pesquisar': 'खोज',
        'Pesquisar por hostname, SO ou processador...': 'होस्टनेम, OS या प्रोसेसर द्वारा खोजें...',
        
        # Machine Details
        'Informações Básicas': 'मूल जानकारी',
        
        # Configurações
        'Exportar PDF': 'PDF निर्यात करें',
        'Sincronizar com Wazuh': 'Wazuh के साथ सिंक करें',
        'Notificações': 'सूचनाएं',
        'Segurança': 'सुरक्षा',
        'Autenticação em Duas Etapas': 'दो-कारक प्रमाणीकरण',
        'Configurar MFA': 'MFA कॉन्फ़िगर करें',
        'Gerar PDF': 'PDF बनाएं',
        'Cancelar': 'रद्द करें',
        'Incluir detalhes completos': 'पूर्ण विवरण शामिल करें',
        'Sincronize os dados do inventário com o Wazuh Manager para manter todas as informações atualizadas.': 'सभी जानकारी अपडेट रखने के लिए इन्वेंट्री डेटा को Wazuh Manager के साथ सिंक करें।',
        'Configure suas preferências de notificação para receber alertas importantes.': 'महत्वपूर्ण अलर्ट प्राप्त करने के लिए अपनी अधिसूचना सेटिंग्स कॉन्फ़िगर करें।',
        'Exportar Relatório PDF': 'PDF रिपोर्ट निर्यात करें',
        'Exportar um relatório completo em PDF com todas as informações do sistema': 'सिस्टम की सभी जानकारी के साथ पूर्ण PDF रिपोर्ट निर्यात करें',
        'Escolha as opções para o relatório:': 'रिपोर्ट के लिए विकल्प चुनें:',
        'Exportar Agora': 'अभी निर्यात करें',
        'Configure a autenticação de dois fatores (MFA) para aumentar a segurança.': 'सुरक्षा बढ़ाने के लिए MFA सक्षम करें।',
        'MFA está ': 'MFA है',
        'habilitada': 'सक्रिय',
        'desabilitada': 'निष्क्रिय',
        'Desabilitar MFA': 'MFA निष्क्रिय करें',
        'Código de 6 dígitos': '6 अंकों का कोड',
        'Habilitar MFA': 'MFA सक्रिय करें',
        'Secret': 'सीक्रेट',
        'Verificar': 'सत्यापित करें',
        'Novo Usuário': 'नया उपयोगकर्ता',
        'Nome de Usuário': 'उपयोगकर्ता नाम',
        'Confirmar Senha': 'पासवर्ड की पुष्टि करें',
        'Criar Usuário': 'उपयोगकर्ता बनाएं',
        'Periodicidade de Sincronização': 'सिंक आवृत्ति',
        'Selecione o intervalo entre as coletas automáticas de dados.': 'स्वचालित डेटा संग्रह के बीच अंतराल चुनें।',
        'Intervalo atual': 'वर्तमान अंतराल',
        'Sincronizar Agora': 'अभी सिंक करें',
        'Salvar Configuração': 'सेटिंग्स सहेजें',
        'Gerar Relatório': 'रिपोर्ट बनाएं',
        'Selecione os parâmetros para a exportação do relatório detalhado em formato PDF.': 'विस्तृत PDF रिपोर्ट के लिए पैरामीटर चुनें।',
        'Incluir detalhes técnicos completos': 'पूर्ण तकनीकी विवरण शामिल करें',
        'Configure a frequência com que o sistema coleta dados do Wazuh API.': 'सिस्टम कितनी बार Wazuh API से डेटा एकत्र करता है, इसे कॉन्फ़िगर करें।',
        'SYNC com Wazuh': 'Wazuh के साथ SYNC',
        'Configurar Sync': 'सिंक कॉन्फ़िगर करें',
        
        
        # Detalhes da máquina
        'Informações Básicas': 'मूल जानकारी',
        'Hardware': 'हार्डवेयर',
        'Network interfaces': 'नेटवर्क इंटरफेस',
        'Network ports': 'नेटवर्क पोर्ट',
        'Network settings': 'नेटवर्क सेटिंग्स',
        'Installed Packages': 'इंस्टॉल किए गए पैकेज',
        'Running Processes': 'चल रहे प्रोसेस',
        'Interface': 'इंटरफेस',
        'MAC': 'MAC',
        'State': 'स्थिति',
        'MTU': 'MTU',
        'Type': 'प्रकार',
        'Local port': 'स्थानीय पोर्ट',
        'Local IP': 'स्थानीय IP',
        'Process': 'प्रोसेस',
        'PID': 'PID',
        'Address': 'पता',
        'Netmask': 'नेटमास्क',
        'Proto': 'प्रोटोकॉल',
        'Broadcast': 'ब्रॉडकास्ट',
        'Name': 'नाम',
        'Version': 'संस्करण',
        'Description': 'विवरण',
        'Architecture': 'आर्किटेक्चर',
        'Format': 'फॉर्मेट',
        'User': 'उपयोगकर्ता',
        'Command': 'कमांड',
    }

    
}