LANGUAGES = {
    ####################
    ## PORTUGUES (BR) ##
    ####################
    'pt': {
        # Menu principal
        'Dashboard': 'Dashboard',
        'Painel': 'Painel',
        'Pesquisa': 'Pesquisa',
        'Configurações': 'Configurações',
        'Sair': 'Sair',
        
        # Login
        'Usuário': 'Usuário',
        'Senha': 'Senha',
        'Entrar': 'Entrar',
        'Credenciais inválidas': 'Credenciais inválidas',
        'Preencha todos os campos': 'Preencha todos os campos',
        'Código MFA inválido': 'Código MFA inválido',
        'Coleta de dados iniciada, aguarde alguns minutos.': 'Coleta de dados iniciada, aguarde alguns minutos.',
        
        #Dashboard
        'Total de Máquinas': 'Total de Máquinas',
        'Ativas': 'Ativas',
        'Inativas': 'Inativas',
        'Atividade': 'Atividade',
        'Processos': 'Processos',
        'Nenhum dado disponível': 'Nenhum dado disponível',
        'Carregando dados...': 'Carregando dados...',
        'Sistemas Operacionais': 'Sistemas Operacionais',
        'Processadores': 'Processadores',
        'Memória RAM': 'Memória RAM',
        'Portas de Rede Mais Comuns': 'Portas de Rede Mais Comuns',
        'Processos Mais Comuns': 'Processos Mais Comuns',
        
        # Painel de máquinas
        'Máquinas': 'Máquinas',
        'Detalhes': 'Detalhes',
        'Voltar': 'Voltar',
        'Hostname': 'Hostname',
        'IP Address': 'Endereço IP',
        'Sistema Operacional': 'Sistema Operacional',
        'Kernel': 'Kernel',
        'Arch': 'Arquitetura',
        'CPU': 'CPU',
        'Núcleos': 'Núcleos',
        'Memória (GB)': 'Memória (GB)',
        'Status': 'Status',
        'Última Atividade': 'Última Atividade',
        'resultado(s) encontrado(s)': 'resultado(s) encontrado(s)',
        'Nenhum resultado encontrado': 'Nenhum resultado encontrado',
        'Tente ajustar sua pesquisa': 'Tente ajustar sua pesquisa',
        'Pesquisar Máquinas': 'Pesquisar Máquinas',
        'Pesquisar': 'Pesquisar',
        'Pesquisar por hostname, SO ou processador...': 'Pesquisar por hostname, SO ou processador...',
        
        
        # Machine Details
        'Informações Básicas': 'Informações Básicas',
        
        # Configurações
        'Exportar PDF': 'Exportar PDF',
        'Sincronizar com Wazuh': 'Sincronizar com Wazuh',
        'Notificações': 'Notificações',
        'Segurança': 'Segurança',
        'Autenticação em Duas Etapas': 'Autenticação em Duas Etapas',
        'Configurar MFA': 'Configurar MFA',
        'Gerar PDF': 'Gerar PDF',
        'Cancelar': 'Cancelar',
        'Incluir detalhes completos': 'Incluir detalhes completos',
        'Sincronize os dados do inventário com o Wazuh Manager para manter todas as informações atualizadas.': 'Sincronize os dados do inventário com o Wazuh Manager para manter todas as informações atualizadas.',
        'Configure suas preferências': 'Configure suas preferências',
        'Exporte um relatório completo': 'Exporte um relatório completo',
        'Configure a autenticação de dois fatores': 'Configure a autenticação de dois fatores',
        'MFA está habilitada': 'MFA está habilitada',
        'MFA está desabilitada': 'MFA está desabilitada',
        'Desabilitar MFA': 'Desabilitar MFA',
        'Habilitar MFA': 'Habilitar MFA',
        'Secret': 'Chave Secreta',
        'Verificar': 'Verificar',
        
        # Detalhes da máquina
        'Informações Básicas': 'Informações Básicas',
        'Hardware': 'Hardware',
        'Network interfaces': 'Interfaces de Rede',
        'Network ports': 'Portas de Rede',
        'Network settings': 'Configurações de Rede',
        'Installed Packages': 'Pacotes Instalados',
        'Running Processes': 'Processos em Execução',
        'Interface': 'Interface',
        'MAC': 'MAC',
        'State': 'Estado',
        'MTU': 'MTU',
        'Type': 'Tipo',
        'Local port': 'Porta Local',
        'Local IP': 'IP Local',
        'Process': 'Processo',
        'PID': 'PID',
        'Address': 'Endereço',
        'Netmask': 'Máscara de Rede',
        'Proto': 'Protocolo',
        'Broadcast': 'Broadcast',
        'Name': 'Nome',
        'Version': 'Versão',
        'Description': 'Descrição',
        'Architecture': 'Arquitetura',
        'Format': 'Formato',
        'User': 'Usuário',
        'Command': 'Comando',
        
    },
    #############
    ## ENGLISH ##
    #############
    'en': {
        # Menu principal
        'Dashboard': 'Dashboard',
        'Painel': 'Machines',
        'Pesquisa': 'Search',
        'Configurações': 'Settings',
        'Sair': 'Logout',
        
        # Login
        'Usuário': 'Username',
        'Senha': 'Password',
        'Entrar': 'Login',
        'Credenciais inválidas': 'Invalid credentials',
        'Preencha todos os campos': 'Please fill all fields',
        'Código MFA inválido': 'Invalid MFA code',
        'Coleta de dados iniciada, aguarde alguns minutos.': 'Data collection started, please wait a few minutes.',
        
        #Dashboard
        'Total de Máquinas': 'Total of Machines',
        'Ativas': 'Active',
        'Inativas': 'Inactive',
        'Atividade': 'Activity',
        'Processos': 'Processes',
        'Nenhum dado disponível': 'No data available',
        'Carregando dados...': 'Loading data...',
        'Sistemas Operacionais': 'Operating Systems',
        'Processadores': 'Processors',
        'Memória RAM': 'RAM Memory',
        'Portas de Rede Mais Comuns': 'Most Common Network Ports',
        'Processos Mais Comuns': 'Most Common Processes',
        
        # Painel de máquinas
        'Máquinas': 'Machines',
        'Detalhes': 'Details',
        'Voltar': 'Back',
        'Hostname': 'Hostname',
        'IP Address': 'IP Address',
        'Sistema Operacional': 'Operating System',
        'Kernel': 'Kernel',
        'Arch': 'Architecture',
        'CPU': 'CPU',
        'Núcleos': 'Cores',
        'Memória (GB)': 'Memory (GB)',
        'Status': 'Status',
        'Última Atividade': 'Last Activity',
        'resultado(s) encontrado(s)': 'result(s) found',
        'Nenhum resultado encontrado': 'No results found',
        'Tente ajustar sua pesquisa': 'Try adjusting your search',
        'Pesquisar Máquinas': 'Search Machines',
        'Pesquisar': 'Search',
        'Pesquisar por hostname, SO ou processador...': 'Search by hostname, OS or processor...',

        
        # Machine Details
        'Informações Básicas': 'Informações Básicas',
        
        # Configurações
        'Exportar Relatório': 'Export PDF',
        'SYNC com Wazuh': 'Sync with Wazuh',
        'Notificações': 'Notifications',
        'Segurança': 'Security',
        'Autenticação em Duas Etapas': 'Two-Factor Authentication',
        'Configurar MFA': 'Configure MFA',
        'Gerar PDF': 'Generate PDF',
        'Cancelar': 'Cancel',
        'Incluir detalhes completos': 'Include full details',
        'Sincronize os dados do inventário com o Wazuh Manager para manter todas as informações atualizadas.': 'Synchronize inventory data with the Wazuh Manager to keep all information up to date.',
        'Configure suas preferências': 'Configure your notification preferences',
        'Exporte um relatório completo': 'Export a complete PDF report',
        'Configure a autenticação de dois fatores': 'Configure two-factor authentication',
        'MFA está habilitada': 'MFA is enabled',
        'MFA está desabilitada': 'MFA is disabled',
        'Desabilitar MFA': 'Disable MFA',
        'Habilitar MFA': 'Enable MFA',
        'Secret': 'Secret',
        'Verificar': 'Verify',
        
        # Detalhes da máquina
        'Informações Básicas': 'Basic Information',
        'Hardware': 'Hardware',
        'Network interfaces': 'Network Interfaces',
        'Network ports': 'Network Ports',
        'Network settings': 'Network Settings',
        'Installed Packages': 'Installed Packages',
        'Running Processes': 'Running Processes',
        'Interface': 'Interface',
        'MAC': 'MAC',
        'State': 'State',
        'MTU': 'MTU',
        'Type': 'Type',
        'Local port': 'Local Port',
        'Local IP': 'Local IP',
        'Process': 'Process',
        'PID': 'PID',
        'Address': 'Address',
        'Netmask': 'Netmask',
        'Proto': 'Protocol',
        'Broadcast': 'Broadcast',
        'Name': 'Name',
        'Version': 'Version',
        'Description': 'Description',
        'Architecture': 'Architecture',
        'Format': 'Format',
        'User': 'User',
        'Command': 'Command',
    },
    ##############
    ## ESPANHOL ##
    ##############
    'es': {
        # Menu principal
        'Dashboard': 'Panel',
        'Painel': 'Máquinas',
        'Pesquisa': 'Búsqueda',
        'Configurações': 'Configuración',
        'Sair': 'Salir',
        
        # Login
        'Usuário': 'Usuario',
        'Senha': 'Contraseña',
        'Entrar': 'Entrar',
        'Credenciais inválidas': 'Credenciales inválidas',
        'Preencha todos os campos': 'Complete todos los campos',
        'Código MFA inválido': 'Código MFA inválido',
        'Coleta de dados iniciada, aguarde alguns minutos.': 'Recolección de datos iniciada, espere unos minutos.',
        
        
        
        #Dashboard
        'Total de Máquinas': 'Total de Maquinas',
        'Ativas': 'Activas',
        'Inativas': 'Inactivas',
        'Atividade': 'Actividad',
        'Processos': 'Procesos',
        'Nenhum dado disponível': 'Ningún dato disponible',
        'Carregando dados...': 'Cargando datos...',
        'Sistemas Operacionais': 'Sistemas Operativos',
        'Processadores': 'Procesadores',
        'Memória RAM': 'Memoria RAM',
        'Portas de Rede Mais Comuns': 'Puertos de Red Mas Comunes',
        'Processos Mais Comunes': 'Procesos Más Comunes',
        
        
        # Painel de máquinas
        'Máquinas': 'Máquinas',
        'Detalhes': 'Detalles',
        'Voltar': 'Volver',
        'Hostname': 'Hostname',
        'IP Address': 'Dirección IP',
        'Sistema Operacional': 'Sistema Operativo',
        'Kernel': 'Kernel',
        'Arch': 'Arquitectura',
        'CPU': 'CPU',
        'Núcleos': 'Núcleos',
        'Memória (GB)': 'Memoria (GB)',
        'Status': 'Estado',
        'Última Atividade': 'Última Actividad',
        'resultado(s) encontrado(s)': 'resultado(s) encontrado(s)',
        'Nenhum resultado encontrado': 'No se encontraron resultados',
        'Tente ajustar sua pesquisa': 'Intente ajustar su búsqueda',
        'Pesquisar Máquinas': 'Buscar máquinas',
        'Pesquisar': 'Buscar',
        'Pesquisar por hostname, SO ou processador...': 'Buscar por hostname, SO o procesador...',
        
        # Configurações
        'Exportar Relatório': 'Exportar PDF',
        'SYNC com Wazuh': 'Sincronizar con Wazuh',
        'Notificações': 'Notificaciones',
        'Segurança': 'Seguridad',
        'Autenticação em Duas Etapas': 'Autenticación en Dos Pasos',
        'Configurar MFA': 'Configurar MFA',
        'Gerar PDF': 'Generar PDF',
        'Cancelar': 'Cancelar',
        'Incluir detalhes completos': 'Incluir detalles completos',
        'Sincronize os dados do inventário': 'Sincronice los datos del inventario',
        'Configure suas preferências': 'Configure sus preferencias',
        'Exporte um relatório completo': 'Exporte un informe completo en PDF',
        'Configure a autenticação de dois fatores': 'Configure autenticación de dos factores',
        'MFA está habilitada': 'MFA está habilitado',
        'MFA está desabilitada': 'MFA está deshabilitado',
        'Desabilitar MFA': 'Deshabilitar MFA',
        'Habilitar MFA': 'Habilitar MFA',
        'Secret': 'Secreto',
        'Verificar': 'Verificar',
        
        # Detalhes da máquina
        'Informações Básicas': 'Información Básica',
        'Hardware': 'Hardware',
        'Network interfaces': 'Interfaces de Red',
        'Network ports': 'Puertos de Red',
        'Network settings': 'Configuraciones de Red',
        'Installed Packages': 'Paquetes Instalados',
        'Running Processes': 'Procesos en Ejecución',
        'Interface': 'Interfaz',
        'MAC': 'MAC',
        'State': 'Estado',
        'MTU': 'MTU',
        'Type': 'Tipo',
        'Local port': 'Puerto Local',
        'Local IP': 'IP Local',
        'Process': 'Proceso',
        'PID': 'PID',
        'Address': 'Dirección',
        'Netmask': 'Máscara de Red',
        'Proto': 'Protocolo',
        'Broadcast': 'Broadcast',
        'Name': 'Nombre',
        'Version': 'Versión',
        'Description': 'Descripción',
        'Architecture': 'Arquitectura',
        'Format': 'Formato',
        'User': 'Usuario',
        'Command': 'Comando',
    }
}